kind: pod
apiVersion: v1
metadata: 
 name: memory limit
 lables:
  project: expense
  env: prod
spec:
 containers:
  - name: nginx
   image: nginx
   resources:
    request: 
     cpu: 100m cpu
     memory: 80mi
    limits:
     cpu: 120m cpu
     memory: 100 mi 